name: Update Status Page

on:
  schedule:
    - cron: '*/10 * * * *' # اجرای خودکار هر ۱۰ دقیقه
  workflow_dispatch: # امکان اجرای دستی از داخل گیت‌هاب

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run Script
        run: python generate_status.py

      - name: Commit and Push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add index.html status.json
          git commit -m "Auto-update status page" || exit 0
          git push
